package es.discoteca.bbdd.bean;

// Generated 01-mar-2013 9:51:56 by Hibernate Tools 4.0.0

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

/**
 * Auxdisint generated by hbm2java
 */
// @Entity
// @Table(name = "auxdisint", catalog = "almacen")

@Entity
@Table(name = "auxdisint")
@AssociationOverrides({
		@AssociationOverride(name = "intdis.disco", joinColumns = @JoinColumn(name = "iddis")),
		@AssociationOverride(name = "intdis.interprete", joinColumns = @JoinColumn(name = "idint")) })
public class Auxdisint implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private AuxdisintId intdis;
	private String instrumento;

	public Auxdisint() {
	}

	public Auxdisint(final AuxdisintId intdis) {
		this.intdis = intdis;
	}

	public Auxdisint(final AuxdisintId intdis, final String instrumento) {
		this.intdis = intdis;
		this.instrumento = instrumento;
	}

	@Column(name = "INSTRUMENTO", length = 45)
	public String getInstrumento() {
		return this.instrumento;
	}

	@EmbeddedId
	public AuxdisintId getIntdis() {
		return this.intdis;
	}

	public void setInstrumento(final String instrumento) {
		this.instrumento = instrumento;
	}

	public void setIntdis(final AuxdisintId intdis) {
		this.intdis = intdis;
	}

}
