package es.discoteca.bbdd.bean;

// Generated 01-mar-2013 9:51:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cancion generated by hbm2java
 */
@Entity
@Table(name = "cancion", catalog = "almacen")
public class Cancion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer ident;
	private String nombre;
	private String duracion;

	public Cancion() {
	}

	public Cancion(final Integer ident) {
		this.ident = ident;
	}

	public Cancion(final Integer ident, final String nombre, final String duracion) {
		this.ident = ident;
		this.nombre = nombre;
		this.duracion = duracion;
	}

	@Column(name = "DURACION", length = 8)
	public String getDuracion() {
		return this.duracion;
	}

	@Id
	@Column(name = "IDENT", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	@Column(name = "NOMBRE", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setDuracion(final String duracion) {
		this.duracion = duracion;
	}

	public void setIdent(final Integer ident) {
		this.ident = ident;
	}

	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

}
