package es.discoteca.bbdd.bean;

// Generated 01-mar-2013 9:51:56 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Interprete generated by hbm2java
 */
@Entity
@Table(name = "interprete", catalog = "almacen")
public class Interprete implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ident;
	private String nombre;
	private Set<Auxdisint> auxdisints = new HashSet<Auxdisint>(0);

	public Interprete() {
	}

	public Interprete(final Integer ident) {
		this.ident = ident;
	}

	public Interprete(final Integer ident, final String nombre, final Set<Auxdisint> auxdisints) {
		this.ident = ident;
		this.nombre = nombre;
		this.auxdisints = auxdisints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intdis.interprete")
	public Set<Auxdisint> getAuxdisints() {
		return this.auxdisints;
	}

	@Id
	@Column(name = "IDENT", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	@Column(name = "NOMBRE", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setAuxdisints(final Set<Auxdisint> auxdisints) {
		this.auxdisints = auxdisints;
	}

	public void setIdent(final Integer ident) {
		this.ident = ident;
	}

	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

}
